/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.Matisse.sesion.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.Matisse.sesion.logic.dto.SesionPageDTO;
import co.edu.uniandes.csw.Matisse.sesion.logic.dto.SesionDTO;
import co.edu.uniandes.csw.Matisse.sesion.persistence.api.ISesionPersistence;
import co.edu.uniandes.csw.Matisse.sesion.persistence.entity.SesionEntity;
import co.edu.uniandes.csw.Matisse.sesion.persistence.converter.SesionConverter;
import static co.edu.uniandes.csw.Matisse.util._TestUtil.*;

@RunWith(Arquillian.class)
public class SesionPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(SesionPersistence.class.getPackage())
				.addPackage(SesionEntity.class.getPackage())
				.addPackage(ISesionPersistence.class.getPackage())
                .addPackage(SesionDTO.class.getPackage())
                .addPackage(SesionConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private ISesionPersistence sesionPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from SesionEntity").executeUpdate();
	}

	private List<SesionEntity> data=new ArrayList<SesionEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			SesionEntity entity=new SesionEntity();
			entity.setName(generateRandom(String.class));
			entity.setEstado(generateRandom(String.class));
			entity.setFecha(generateRandom(Date.class));
			entity.setSemanaAnual(generateRandom(Integer.class));
			entity.setDia(generateRandom(String.class));
			entity.setEstudianteId(generateRandom(Long.class));
			entity.setMonitorId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createSesionTest(){
		SesionDTO dto=new SesionDTO();
		dto.setName(generateRandom(String.class));
		dto.setEstado(generateRandom(String.class));
dto.setFecha(generateRandomDate());
		dto.setSemanaAnual(generateRandom(Integer.class));
		dto.setDia(generateRandom(String.class));
		dto.setEstudianteId(generateRandom(Long.class));
		dto.setMonitorId(generateRandom(Long.class));
		
		SesionDTO result=sesionPersistence.createSesion(dto);
		
		Assert.assertNotNull(result);
		
		SesionEntity entity=em.find(SesionEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getEstado(), entity.getEstado());
Assert.assertEquals(parseDate(dto.getFecha()), entity.getFecha());	
		Assert.assertEquals(dto.getSemanaAnual(), entity.getSemanaAnual());
		Assert.assertEquals(dto.getDia(), entity.getDia());
		Assert.assertEquals(dto.getEstudianteId(), entity.getEstudianteId());
		Assert.assertEquals(dto.getMonitorId(), entity.getMonitorId());
	}
	
	@Test
	public void getSesionsTest(){
		List<SesionDTO> list=sesionPersistence.getSesions();
		Assert.assertEquals(list.size(), data.size());
        for(SesionDTO dto:list){
        	boolean found=false;
            for(SesionEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getSesionTest(){
		SesionEntity entity=data.get(0);
		SesionDTO dto=sesionPersistence.getSesion(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getEstado(), dto.getEstado());
		Assert.assertEquals(entity.getSemanaAnual(), dto.getSemanaAnual());
		Assert.assertEquals(entity.getDia(), dto.getDia());
		Assert.assertEquals(entity.getEstudianteId(), dto.getEstudianteId());
		Assert.assertEquals(entity.getMonitorId(), dto.getMonitorId());
        
	}
	
	@Test
	public void deleteSesionTest(){
		SesionEntity entity=data.get(0);
		sesionPersistence.deleteSesion(entity.getId());
        SesionEntity deleted=em.find(SesionEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateSesionTest(){
		SesionEntity entity=data.get(0);
		
		SesionDTO dto=new SesionDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setEstado(generateRandom(String.class));
dto.setFecha(generateRandomDate());
		dto.setSemanaAnual(generateRandom(Integer.class));
		dto.setDia(generateRandom(String.class));
		dto.setEstudianteId(generateRandom(Long.class));
		dto.setMonitorId(generateRandom(Long.class));
		
		
		sesionPersistence.updateSesion(dto);
		
		
		SesionEntity resp=em.find(SesionEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getEstado(), resp.getEstado());	
Assert.assertEquals(parseDate(dto.getFecha()), resp.getFecha());
		Assert.assertEquals(dto.getSemanaAnual(), resp.getSemanaAnual());	
		Assert.assertEquals(dto.getDia(), resp.getDia());	
		Assert.assertEquals(dto.getEstudianteId(), resp.getEstudianteId());	
		Assert.assertEquals(dto.getMonitorId(), resp.getMonitorId());	
	}
	
	@Test
	public void getSesionPaginationTest(){
		//Page 1
		SesionPageDTO dto1=sesionPersistence.getSesions(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        SesionPageDTO dto2=sesionPersistence.getSesions(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(SesionDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(SesionEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(SesionDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(SesionEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}