/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410261249*/

package co.edu.uniandes.csw.Matisse.pregunta.master.logic.ejb;

import co.edu.uniandes.csw.Matisse.respuesta.logic.dto.RespuestaDTO;
import co.edu.uniandes.csw.Matisse.respuesta.persistence.api.IRespuestaPersistence;
import co.edu.uniandes.csw.Matisse.pregunta.logic.dto.PreguntaDTO;
import co.edu.uniandes.csw.Matisse.pregunta.master.logic.api._IPreguntaMasterLogicService;
import co.edu.uniandes.csw.Matisse.pregunta.master.logic.dto.PreguntaMasterDTO;
import co.edu.uniandes.csw.Matisse.pregunta.master.persistence.api.IPreguntaMasterPersistence;
import co.edu.uniandes.csw.Matisse.pregunta.master.persistence.entity.PreguntarespuestaEntity;
import co.edu.uniandes.csw.Matisse.pregunta.persistence.api.IPreguntaPersistence;
import javax.inject.Inject;

public abstract class _PreguntaMasterLogicService implements _IPreguntaMasterLogicService {

    @Inject
    protected IPreguntaPersistence preguntaPersistance;
    @Inject
    protected IPreguntaMasterPersistence preguntaMasterPersistance;
    @Inject
    protected IRespuestaPersistence respuestaPersistance;

    public PreguntaMasterDTO createMasterPregunta(PreguntaMasterDTO pregunta) {
        PreguntaDTO persistedPreguntaDTO = preguntaPersistance.createPregunta(pregunta.getPreguntaEntity());
        if (pregunta.getCreaterespuesta() != null) {
            for (RespuestaDTO respuestaDTO : pregunta.getCreaterespuesta()) {
                RespuestaDTO createdRespuestaDTO = respuestaPersistance.createRespuesta(respuestaDTO);
                PreguntarespuestaEntity preguntaRespuestaEntity = new PreguntarespuestaEntity(persistedPreguntaDTO.getId(), createdRespuestaDTO.getId());
                preguntaMasterPersistance.createPreguntarespuestaEntity(preguntaRespuestaEntity);
            }
        }
        // update respuesta
        if (pregunta.getUpdaterespuesta() != null) {
            for (RespuestaDTO respuestaDTO : pregunta.getUpdaterespuesta()) {
                respuestaPersistance.updateRespuesta(respuestaDTO);
                PreguntarespuestaEntity preguntaRespuestaEntity = new PreguntarespuestaEntity(persistedPreguntaDTO.getId(), respuestaDTO.getId());
                preguntaMasterPersistance.createPreguntarespuestaEntity(preguntaRespuestaEntity);
            }
        }
        return pregunta;
    }

    public PreguntaMasterDTO getMasterPregunta(Long id) {
        return preguntaMasterPersistance.getPregunta(id);
    }

    public void deleteMasterPregunta(Long id) {
        preguntaPersistance.deletePregunta(id);
    }

    public void updateMasterPregunta(PreguntaMasterDTO pregunta) {
        preguntaPersistance.updatePregunta(pregunta.getPreguntaEntity());

        //---- FOR RELATIONSHIP
        // delete respuesta
        if (pregunta.getDeleterespuesta() != null) {
            for (RespuestaDTO respuestaDTO : pregunta.getDeleterespuesta()) {
                preguntaMasterPersistance.deletePreguntarespuestaEntity(pregunta.getPreguntaEntity().getId(), respuestaDTO.getId());
            }
        }
        // persist new respuesta
        if (pregunta.getCreaterespuesta() != null) {
            for (RespuestaDTO respuestaDTO : pregunta.getCreaterespuesta()) {
                PreguntarespuestaEntity preguntaRespuestaEntity = new PreguntarespuestaEntity(pregunta.getPreguntaEntity().getId(), respuestaDTO.getId());
                preguntaMasterPersistance.createPreguntarespuestaEntity(preguntaRespuestaEntity);
            }
        }
        // update respuesta
        if (pregunta.getUpdaterespuesta() != null) {
            for (RespuestaDTO respuestaDTO : pregunta.getUpdaterespuesta()) {
                preguntaMasterPersistance.deletePreguntarespuestaEntity(pregunta.getPreguntaEntity().getId(), respuestaDTO.getId());
                respuestaPersistance.updateRespuesta(respuestaDTO);
                PreguntarespuestaEntity preguntaRespuestaEntity = new PreguntarespuestaEntity(pregunta.getId(), respuestaDTO.getId());
                preguntaMasterPersistance.createPreguntarespuestaEntity(preguntaRespuestaEntity);
                
            }
        }
    }
}
