/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410261249*/

package co.edu.uniandes.csw.Matisse.resultado.master.logic.ejb;

import co.edu.uniandes.csw.Matisse.entradas.logic.dto.EntradasDTO;
import co.edu.uniandes.csw.Matisse.entradas.persistence.api.IEntradasPersistence;
import co.edu.uniandes.csw.Matisse.resultado.logic.dto.ResultadoDTO;
import co.edu.uniandes.csw.Matisse.resultado.master.logic.api._IResultadoMasterLogicService;
import co.edu.uniandes.csw.Matisse.resultado.master.logic.dto.ResultadoMasterDTO;
import co.edu.uniandes.csw.Matisse.resultado.master.persistence.api.IResultadoMasterPersistence;
import co.edu.uniandes.csw.Matisse.resultado.master.persistence.entity.ResultadoentradasEntity;
import co.edu.uniandes.csw.Matisse.resultado.persistence.api.IResultadoPersistence;
import javax.inject.Inject;

public abstract class _ResultadoMasterLogicService implements _IResultadoMasterLogicService {

    @Inject
    protected IResultadoPersistence resultadoPersistance;
    @Inject
    protected IResultadoMasterPersistence resultadoMasterPersistance;
    @Inject
    protected IEntradasPersistence entradasPersistance;

    public ResultadoMasterDTO createMasterResultado(ResultadoMasterDTO resultado) {
        ResultadoDTO persistedResultadoDTO = resultadoPersistance.createResultado(resultado.getResultadoEntity());
        if (resultado.getCreateentradas() != null) {
            for (EntradasDTO entradasDTO : resultado.getCreateentradas()) {
                EntradasDTO createdEntradasDTO = entradasPersistance.createEntradas(entradasDTO);
                ResultadoentradasEntity resultadoEntradasEntity = new ResultadoentradasEntity(persistedResultadoDTO.getId(), createdEntradasDTO.getId());
                resultadoMasterPersistance.createResultadoentradasEntity(resultadoEntradasEntity);
            }
        }
        // update entradas
        if (resultado.getUpdateentradas() != null) {
            for (EntradasDTO entradasDTO : resultado.getUpdateentradas()) {
                entradasPersistance.updateEntradas(entradasDTO);
                ResultadoentradasEntity resultadoEntradasEntity = new ResultadoentradasEntity(persistedResultadoDTO.getId(), entradasDTO.getId());
                resultadoMasterPersistance.createResultadoentradasEntity(resultadoEntradasEntity);
            }
        }
        return resultado;
    }

    public ResultadoMasterDTO getMasterResultado(Long id) {
        return resultadoMasterPersistance.getResultado(id);
    }

    public void deleteMasterResultado(Long id) {
        resultadoPersistance.deleteResultado(id);
    }

    public void updateMasterResultado(ResultadoMasterDTO resultado) {
        resultadoPersistance.updateResultado(resultado.getResultadoEntity());

        //---- FOR RELATIONSHIP
        // persist new entradas
        if (resultado.getCreateentradas() != null) {
            for (EntradasDTO entradasDTO : resultado.getCreateentradas()) {
                EntradasDTO createdEntradasDTO = entradasPersistance.createEntradas(entradasDTO);
                ResultadoentradasEntity resultadoEntradasEntity = new ResultadoentradasEntity(resultado.getResultadoEntity().getId(), createdEntradasDTO.getId());
                resultadoMasterPersistance.createResultadoentradasEntity(resultadoEntradasEntity);
            }
        }
        // update entradas
        if (resultado.getUpdateentradas() != null) {
            for (EntradasDTO entradasDTO : resultado.getUpdateentradas()) {
                entradasPersistance.updateEntradas(entradasDTO);
            }
        }
        // delete entradas
        if (resultado.getDeleteentradas() != null) {
            for (EntradasDTO entradasDTO : resultado.getDeleteentradas()) {
                resultadoMasterPersistance.deleteResultadoentradasEntity(resultado.getResultadoEntity().getId(), entradasDTO.getId());
                entradasPersistance.deleteEntradas(entradasDTO.getId());
            }
        }
    }
}
