/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201411201032*/

package co.edu.uniandes.csw.Matisse.pregunta.master.persistence.entity;

import co.edu.uniandes.csw.Matisse.respuesta.persistence.entity.RespuestaEntity;
import co.edu.uniandes.csw.Matisse.pregunta.persistence.entity.PreguntaEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(PreguntarespuestaEntityId.class)
@NamedQueries({
    @NamedQuery(name = "PreguntarespuestaEntity.getByMasterId", query = "SELECT  u FROM PreguntarespuestaEntity u WHERE u.preguntaId=:preguntaId"),
    @NamedQuery(name = "PreguntarespuestaEntity.deletePreguntarespuestaEntity", query = "DELETE FROM PreguntarespuestaEntity u WHERE u.preguntaId=:preguntaId and  u.respuestaId=:respuestaId")
})
public class PreguntarespuestaEntity implements Serializable {

    @Id
    @Column(name = "preguntaId")
    private Long preguntaId;
    @Id
    @Column(name = "respuestaId")
    private Long respuestaId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "preguntaId", referencedColumnName = "id")
    @JoinFetch
    private RespuestaEntity preguntaIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "respuestaId", referencedColumnName = "id")
    @JoinFetch
    private RespuestaEntity respuestaIdEntity; 

    public PreguntarespuestaEntity() {
    }

    public PreguntarespuestaEntity(Long preguntaId, Long respuestaId) {
        this.preguntaId =preguntaId;
        this.respuestaId = respuestaId;
    }

    public Long getPreguntaId() {
        return preguntaId;
    }

    public void setPreguntaId(Long preguntaId) {
        this.preguntaId = preguntaId;
    }

    public Long getRespuestaId() {
        return respuestaId;
    }

    public void setRespuestaId(Long respuestaId) {
        this.respuestaId = respuestaId;
    }

    public RespuestaEntity getPreguntaIdEntity() {
        return preguntaIdEntity;
    }

    public void setPreguntaIdEntity(RespuestaEntity preguntaIdEntity) {
        this.preguntaIdEntity = preguntaIdEntity;
    }

    public RespuestaEntity getRespuestaIdEntity() {
        return respuestaIdEntity;
    }

    public void setRespuestaIdEntity(RespuestaEntity respuestaIdEntity) {
        this.respuestaIdEntity = respuestaIdEntity;
    }

}
