/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201408112050*/

package co.edu.uniandes.csw.Matisse.pregunta.master.persistence;
import co.edu.uniandes.csw.Matisse.respuesta.logic.dto.RespuestaDTO;
import co.edu.uniandes.csw.Matisse.pregunta.master.persistence.entity.PreguntarespuestaEntity;
import co.edu.uniandes.csw.Matisse.respuesta.persistence.converter.RespuestaConverter;
import co.edu.uniandes.csw.Matisse.pregunta.logic.dto.PreguntaDTO;
import co.edu.uniandes.csw.Matisse.pregunta.master.logic.dto.PreguntaMasterDTO;
import co.edu.uniandes.csw.Matisse.pregunta.master.persistence.api._IPreguntaMasterPersistence;
import co.edu.uniandes.csw.Matisse.pregunta.persistence.api.IPreguntaPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _PreguntaMasterPersistence implements _IPreguntaMasterPersistence {

  	@PersistenceContext(unitName="CupiTallerPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IPreguntaPersistence preguntaPersistence;  

    public PreguntaMasterDTO getPregunta(Long preguntaId) {
        PreguntaMasterDTO preguntaMasterDTO = new PreguntaMasterDTO();
        PreguntaDTO pregunta = preguntaPersistence.getPregunta(preguntaId);
        preguntaMasterDTO.setPreguntaEntity(pregunta);
        preguntaMasterDTO.setListrespuesta(getPreguntarespuestaEntityList(preguntaId));
        return preguntaMasterDTO;
    }

    public PreguntarespuestaEntity createPreguntarespuestaEntity(PreguntarespuestaEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deletePreguntarespuestaEntity(Long preguntaId, Long respuestaId) {
        Query q = entityManager.createNamedQuery("PreguntarespuestaEntity.deletePreguntarespuestaEntity");
        q.setParameter("preguntaId", preguntaId);
        q.setParameter("respuestaId", respuestaId);
        q.executeUpdate();
    }

    public List<RespuestaDTO> getPreguntarespuestaEntityList(Long preguntaId) {
        ArrayList<RespuestaDTO> resp = new ArrayList<RespuestaDTO>();
        Query q = entityManager.createNamedQuery("PreguntarespuestaEntity.getByMasterId");
        q.setParameter("preguntaId",preguntaId);
        List<PreguntarespuestaEntity> qResult =  q.getResultList();
        for (PreguntarespuestaEntity entity : qResult) { 
            if(entity.getRespuestaIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(RespuestaConverter.entity2PersistenceDTO(entity.getRespuestaIdEntity()));
        }
        return resp;
    }

}
