/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201408112050*/

package co.edu.uniandes.csw.Matisse.encuesta.master.persistence;
import co.edu.uniandes.csw.Matisse.pregunta.logic.dto.PreguntaDTO;
import co.edu.uniandes.csw.Matisse.encuesta.master.persistence.entity.EncuestapreguntasEntity;
import co.edu.uniandes.csw.Matisse.pregunta.persistence.converter.PreguntaConverter;
import co.edu.uniandes.csw.Matisse.encuesta.logic.dto.EncuestaDTO;
import co.edu.uniandes.csw.Matisse.encuesta.master.logic.dto.EncuestaMasterDTO;
import co.edu.uniandes.csw.Matisse.encuesta.master.persistence.api._IEncuestaMasterPersistence;
import co.edu.uniandes.csw.Matisse.encuesta.persistence.api.IEncuestaPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _EncuestaMasterPersistence implements _IEncuestaMasterPersistence {

  	@PersistenceContext(unitName="CupiTallerPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IEncuestaPersistence encuestaPersistence;  

    public EncuestaMasterDTO getEncuesta(Long encuestaId) {
        EncuestaMasterDTO encuestaMasterDTO = new EncuestaMasterDTO();
        EncuestaDTO encuesta = encuestaPersistence.getEncuesta(encuestaId);
        encuestaMasterDTO.setEncuestaEntity(encuesta);
        encuestaMasterDTO.setListpreguntas(getEncuestapreguntasEntityList(encuestaId));
        return encuestaMasterDTO;
    }

    public EncuestapreguntasEntity createEncuestapreguntasEntity(EncuestapreguntasEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteEncuestapreguntasEntity(Long encuestaId, Long preguntasId) {
        Query q = entityManager.createNamedQuery("EncuestapreguntasEntity.deleteEncuestapreguntasEntity");
        q.setParameter("encuestaId", encuestaId);
        q.setParameter("preguntasId", preguntasId);
        q.executeUpdate();
    }

    public List<PreguntaDTO> getEncuestapreguntasEntityList(Long encuestaId) {
        ArrayList<PreguntaDTO> resp = new ArrayList<PreguntaDTO>();
        Query q = entityManager.createNamedQuery("EncuestapreguntasEntity.getByMasterId");
        q.setParameter("encuestaId",encuestaId);
        List<EncuestapreguntasEntity> qResult =  q.getResultList();
        for (EncuestapreguntasEntity entity : qResult) { 
            if(entity.getPreguntasIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(PreguntaConverter.entity2PersistenceDTO(entity.getPreguntasIdEntity()));
        }
        return resp;
    }

}
