/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201411201032*/

package co.edu.uniandes.csw.Matisse.resultado.master.logic.dto;

import co.edu.uniandes.csw.Matisse.entradas.logic.dto.EntradasDTO;
import co.edu.uniandes.csw.Matisse.resultado.logic.dto.ResultadoDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _ResultadoMasterDTO {

 
    protected ResultadoDTO resultadoEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public ResultadoDTO getResultadoEntity() {
        return resultadoEntity;
    }

    public void setResultadoEntity(ResultadoDTO resultadoEntity) {
        this.resultadoEntity = resultadoEntity;
    }
    
    public List<EntradasDTO> createentradas;
    public List<EntradasDTO> updateentradas;
    public List<EntradasDTO> deleteentradas;
    public List<EntradasDTO> listentradas;	
	
	
	
    public List<EntradasDTO> getCreateentradas(){ return createentradas; };
    public void setCreateentradas(List<EntradasDTO> createentradas){ this.createentradas=createentradas; };
    public List<EntradasDTO> getUpdateentradas(){ return updateentradas; };
    public void setUpdateentradas(List<EntradasDTO> updateentradas){ this.updateentradas=updateentradas; };
    public List<EntradasDTO> getDeleteentradas(){ return deleteentradas; };
    public void setDeleteentradas(List<EntradasDTO> deleteentradas){ this.deleteentradas=deleteentradas; };
    public List<EntradasDTO> getListentradas(){ return listentradas; };
    public void setListentradas(List<EntradasDTO> listentradas){ this.listentradas=listentradas; };	
	
	
}

