/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201411201032*/

package co.edu.uniandes.csw.Matisse.resultado.master.persistence.entity;

import co.edu.uniandes.csw.Matisse.entradas.persistence.entity.EntradasEntity;
import co.edu.uniandes.csw.Matisse.resultado.persistence.entity.ResultadoEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(ResultadoentradasEntityId.class)
@NamedQueries({
    @NamedQuery(name = "ResultadoentradasEntity.getByMasterId", query = "SELECT  u FROM ResultadoentradasEntity u WHERE u.resultadoId=:resultadoId"),
    @NamedQuery(name = "ResultadoentradasEntity.deleteResultadoentradasEntity", query = "DELETE FROM ResultadoentradasEntity u WHERE u.resultadoId=:resultadoId and  u.entradasId=:entradasId")
})
public class ResultadoentradasEntity implements Serializable {

    @Id
    @Column(name = "resultadoId")
    private Long resultadoId;
    @Id
    @Column(name = "entradasId")
    private Long entradasId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "resultadoId", referencedColumnName = "id")
    @JoinFetch
    private EntradasEntity resultadoIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "entradasId", referencedColumnName = "id")
    @JoinFetch
    private EntradasEntity entradasIdEntity; 

    public ResultadoentradasEntity() {
    }

    public ResultadoentradasEntity(Long resultadoId, Long entradasId) {
        this.resultadoId =resultadoId;
        this.entradasId = entradasId;
    }

    public Long getResultadoId() {
        return resultadoId;
    }

    public void setResultadoId(Long resultadoId) {
        this.resultadoId = resultadoId;
    }

    public Long getEntradasId() {
        return entradasId;
    }

    public void setEntradasId(Long entradasId) {
        this.entradasId = entradasId;
    }

    public EntradasEntity getResultadoIdEntity() {
        return resultadoIdEntity;
    }

    public void setResultadoIdEntity(EntradasEntity resultadoIdEntity) {
        this.resultadoIdEntity = resultadoIdEntity;
    }

    public EntradasEntity getEntradasIdEntity() {
        return entradasIdEntity;
    }

    public void setEntradasIdEntity(EntradasEntity entradasIdEntity) {
        this.entradasIdEntity = entradasIdEntity;
    }

}
