/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201408112050*/

package co.edu.uniandes.csw.Matisse.encuestaestudiante.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.Matisse.encuestaestudiante.logic.dto.EncuestaEstudianteDTO;
import co.edu.uniandes.csw.Matisse.encuestaestudiante.persistence.entity.EncuestaEstudianteEntity;

public abstract class _EncuestaEstudianteConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static EncuestaEstudianteDTO entity2PersistenceDTO(EncuestaEstudianteEntity entity){
		if (entity != null) {
			EncuestaEstudianteDTO dto = new EncuestaEstudianteDTO();
					dto.setName(entity.getName());
					dto.setId(entity.getId());
 
			    if(entity.getFecha() != null){
					dto.setFecha(DATE_FORMAT.format(entity.getFecha()));
				}	
					dto.setUsuarioEncuestado(entity.getUsuarioEncuestado());
			return dto;
		}else{
			return null;
		}
	}
	
	public static EncuestaEstudianteEntity persistenceDTO2Entity(EncuestaEstudianteDTO dto){
		if(dto!=null){
			EncuestaEstudianteEntity entity=new EncuestaEstudianteEntity();
					entity.setName(dto.getName());
			
					entity.setId(dto.getId());
			
 
			      try{ 
			        if(dto.getFecha() != null){
						entity.setFecha(DATE_FORMAT.parse(dto.getFecha()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_EncuestaEstudianteConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setUsuarioEncuestado(dto.getUsuarioEncuestado());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<EncuestaEstudianteDTO> entity2PersistenceDTOList(List<EncuestaEstudianteEntity> entities){
		List<EncuestaEstudianteDTO> dtos=new ArrayList<EncuestaEstudianteDTO>();
		for(EncuestaEstudianteEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<EncuestaEstudianteEntity> persistenceDTO2EntityList(List<EncuestaEstudianteDTO> dtos){
		List<EncuestaEstudianteEntity> entities=new ArrayList<EncuestaEstudianteEntity>();
		for(EncuestaEstudianteDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}