/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.Matisse.sesion.service;

import co.edu.uniandes.csw.Matisse.Semana.logic.dto.SemanaDTO;
import co.edu.uniandes.csw.Matisse.entradas.logic.dto.EntradasDTO;
import co.edu.uniandes.csw.Matisse.sesion.logic.dto.SesionPageDTO;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.ejb.Stateless;
import javax.ws.rs.Consumes;
import javax.ws.rs.DefaultValue;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;
import javax.ws.rs.core.UriInfo;

@Path("/Sesion")
@Stateless
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class SesionService extends _SesionService {
    @Context
    UriInfo uriInfo;

    @GET
    @Path("estadistica")
    public SemanaDTO darEstadisticasPorSemana(@QueryParam("semanaAnual")Integer semana) {
        if(semana==null){
            semana = sesionLogicService.darUltimaSemana();
        }
        return sesionLogicService.darEstadisticaPorSemana(semana);
    }
    
    @GET
    @Path("compararSemanas")
    public List<SemanaDTO> compararEstadisticasPorSemana() {
        ArrayList<SemanaDTO> respuesta = new ArrayList<SemanaDTO>();
        MultivaluedMap<String, String> queryParams = uriInfo.getQueryParameters();
        Collection<List<String>> semanas = queryParams.values();
        if(semanas.size()==0){
            int ultima = sesionLogicService.darUltimaSemana();
            for(int i = 0; i<4 && ultima>0;i++){
                respuesta.add(darEstadisticasPorSemana(ultima));
                ultima--;
            }
        }
        else{
            for(String semana: semanas.iterator().next()){
                respuesta.add(darEstadisticasPorSemana(Integer.parseInt(semana)));
            }
        }
        
        return respuesta; 
    }
    
    @GET
    @Path("sesionesSemana")
    public SesionPageDTO getSesionesSemana(@QueryParam("semanaAnual")Integer semana,@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
	System.out.println("entro sesiones por semana");
        return sesionLogicService.getSesionesSemana(page, maxRecords, semana);
    }
    
    @GET
    @Path("opcionesSemana")
    public List<EntradasDTO>darSemanas(){
        return sesionLogicService.darSemanas();
    }
    
    @GET
    @Path("sesionesMonitor")
    public SemanaDTO darEstadisticasPorMonitor(@QueryParam("idMonitor")Integer monitor) {
        return sesionLogicService.darEstadisticaPorMonitor(monitor);
    }
    
    @GET
    @Path("/report")
    @Produces("application/pdf")
    public byte[] getReport(){
        return sesionLogicService.getReport();
    }
    
}