/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201408112050*/

package co.edu.uniandes.csw.Matisse.encuesta.master.logic.dto;

import co.edu.uniandes.csw.Matisse.pregunta.logic.dto.PreguntaDTO;
import co.edu.uniandes.csw.Matisse.encuesta.logic.dto.EncuestaDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _EncuestaMasterDTO {

 
    protected EncuestaDTO encuestaEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public EncuestaDTO getEncuestaEntity() {
        return encuestaEntity;
    }

    public void setEncuestaEntity(EncuestaDTO encuestaEntity) {
        this.encuestaEntity = encuestaEntity;
    }
    
    public List<PreguntaDTO> createpreguntas;
    public List<PreguntaDTO> updatepreguntas;
    public List<PreguntaDTO> deletepreguntas;
    public List<PreguntaDTO> listpreguntas;	
	
	
	
    public List<PreguntaDTO> getCreatepreguntas(){ return createpreguntas; };
    public void setCreatepreguntas(List<PreguntaDTO> createpreguntas){ this.createpreguntas=createpreguntas; };
    public List<PreguntaDTO> getUpdatepreguntas(){ return updatepreguntas; };
    public void setUpdatepreguntas(List<PreguntaDTO> updatepreguntas){ this.updatepreguntas=updatepreguntas; };
    public List<PreguntaDTO> getDeletepreguntas(){ return deletepreguntas; };
    public void setDeletepreguntas(List<PreguntaDTO> deletepreguntas){ this.deletepreguntas=deletepreguntas; };
    public List<PreguntaDTO> getListpreguntas(){ return listpreguntas; };
    public void setListpreguntas(List<PreguntaDTO> listpreguntas){ this.listpreguntas=listpreguntas; };	
	
	
}

