/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201408112050*/

package co.edu.uniandes.csw.Matisse.respuestaabierta.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.Matisse.respuestaabierta.logic.dto.RespuestaAbiertaDTO;
import co.edu.uniandes.csw.Matisse.respuestaabierta.persistence.entity.RespuestaAbiertaEntity;

public abstract class _RespuestaAbiertaConverter {

	public static RespuestaAbiertaDTO entity2PersistenceDTO(RespuestaAbiertaEntity entity){
		if (entity != null) {
			RespuestaAbiertaDTO dto = new RespuestaAbiertaDTO();
					dto.setContenido(entity.getContenido());
					dto.setId(entity.getId());
					dto.setName(entity.getName());
			return dto;
		}else{
			return null;
		}
	}
	
	public static RespuestaAbiertaEntity persistenceDTO2Entity(RespuestaAbiertaDTO dto){
		if(dto!=null){
			RespuestaAbiertaEntity entity=new RespuestaAbiertaEntity();
					entity.setContenido(dto.getContenido());
			
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<RespuestaAbiertaDTO> entity2PersistenceDTOList(List<RespuestaAbiertaEntity> entities){
		List<RespuestaAbiertaDTO> dtos=new ArrayList<RespuestaAbiertaDTO>();
		for(RespuestaAbiertaEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<RespuestaAbiertaEntity> persistenceDTO2EntityList(List<RespuestaAbiertaDTO> dtos){
		List<RespuestaAbiertaEntity> entities=new ArrayList<RespuestaAbiertaEntity>();
		for(RespuestaAbiertaDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}