/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.Matisse.sesion.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.Matisse.sesion.logic.dto.SesionDTO;
import co.edu.uniandes.csw.Matisse.sesion.persistence.entity.SesionEntity;

public abstract class _SesionConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static SesionDTO entity2PersistenceDTO(SesionEntity entity){
		if (entity != null) {
			SesionDTO dto = new SesionDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setEstado(entity.getEstado());
 
			    if(entity.getFecha() != null){
					dto.setFecha(DATE_FORMAT.format(entity.getFecha()));
				}	
					dto.setSemanaAnual(entity.getSemanaAnual());
					dto.setDia(entity.getDia());
					dto.setEstudianteId(entity.getEstudianteId());
					dto.setMonitorId(entity.getMonitorId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static SesionEntity persistenceDTO2Entity(SesionDTO dto){
		if(dto!=null){
			SesionEntity entity=new SesionEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setEstado(dto.getEstado());
			
 
			      try{ 
			        if(dto.getFecha() != null){
						entity.setFecha(DATE_FORMAT.parse(dto.getFecha()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_SesionConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setSemanaAnual(dto.getSemanaAnual());
			
					entity.setDia(dto.getDia());
			
					entity.setEstudianteId(dto.getEstudianteId());
			
					entity.setMonitorId(dto.getMonitorId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<SesionDTO> entity2PersistenceDTOList(List<SesionEntity> entities){
		List<SesionDTO> dtos=new ArrayList<SesionDTO>();
		for(SesionEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<SesionEntity> persistenceDTO2EntityList(List<SesionDTO> dtos){
		List<SesionEntity> entities=new ArrayList<SesionEntity>();
		for(SesionDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}