/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.Matisse.monitor.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.Matisse.monitor.logic.dto.MonitorPageDTO;
import co.edu.uniandes.csw.Matisse.monitor.logic.dto.MonitorDTO;
import co.edu.uniandes.csw.Matisse.monitor.logic.api.IMonitorLogicService;
import co.edu.uniandes.csw.Matisse.monitor.persistence.MonitorPersistence;
import co.edu.uniandes.csw.Matisse.monitor.persistence.api.IMonitorPersistence;
import co.edu.uniandes.csw.Matisse.monitor.persistence.entity.MonitorEntity;
import co.edu.uniandes.csw.Matisse.monitor.persistence.converter.MonitorConverter;
import static co.edu.uniandes.csw.Matisse.util._TestUtil.*;

@RunWith(Arquillian.class)
public class MonitorLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(MonitorLogicService.class.getPackage())
				.addPackage(IMonitorLogicService.class.getPackage())
				.addPackage(MonitorPersistence.class.getPackage())
				.addPackage(MonitorEntity.class.getPackage())
				.addPackage(IMonitorPersistence.class.getPackage())
                .addPackage(MonitorDTO.class.getPackage())
                .addPackage(MonitorConverter.class.getPackage())
                .addPackage(MonitorEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IMonitorLogicService monitorLogicService;
	
	@Inject
	private IMonitorPersistence monitorPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<MonitorDTO> dtos=monitorPersistence.getMonitors();
		for(MonitorDTO dto:dtos){
			monitorPersistence.deleteMonitor(dto.getId());
		}
	}

	private List<MonitorDTO> data=new ArrayList<MonitorDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			MonitorDTO pdto=new MonitorDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setActivo(generateRandom(Boolean.class));
			pdto.setUsuario(generateRandom(String.class));
			pdto.setPuntosNegativos(generateRandom(Integer.class));
			pdto.setCarrera(generateRandom(String.class));
			pdto=monitorPersistence.createMonitor(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createMonitorTest(){
		MonitorDTO ldto=new MonitorDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setActivo(generateRandom(Boolean.class));
		ldto.setUsuario(generateRandom(String.class));
		ldto.setPuntosNegativos(generateRandom(Integer.class));
		ldto.setCarrera(generateRandom(String.class));
		
		
		MonitorDTO result=monitorLogicService.createMonitor(ldto);
		
		Assert.assertNotNull(result);
		
		MonitorDTO pdto=monitorPersistence.getMonitor(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getActivo(), pdto.getActivo());	
		Assert.assertEquals(ldto.getUsuario(), pdto.getUsuario());	
		Assert.assertEquals(ldto.getPuntosNegativos(), pdto.getPuntosNegativos());	
		Assert.assertEquals(ldto.getCarrera(), pdto.getCarrera());	
	}
	
	@Test
	public void getMonitorsTest(){
		List<MonitorDTO> list=monitorLogicService.getMonitors();
		Assert.assertEquals(list.size(), data.size());
        for(MonitorDTO ldto:list){
        	boolean found=false;
            for(MonitorDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getMonitorTest(){
		MonitorDTO pdto=data.get(0);
		MonitorDTO ldto=monitorLogicService.getMonitor(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getActivo(), ldto.getActivo());
		Assert.assertEquals(pdto.getUsuario(), ldto.getUsuario());
		Assert.assertEquals(pdto.getPuntosNegativos(), ldto.getPuntosNegativos());
		Assert.assertEquals(pdto.getCarrera(), ldto.getCarrera());
        
	}
	
	@Test
	public void deleteMonitorTest(){
		MonitorDTO pdto=data.get(0);
		monitorLogicService.deleteMonitor(pdto.getId());
        MonitorDTO deleted=monitorPersistence.getMonitor(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateMonitorTest(){
		MonitorDTO pdto=data.get(0);
		
		MonitorDTO ldto=new MonitorDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setActivo(generateRandom(Boolean.class));
		ldto.setUsuario(generateRandom(String.class));
		ldto.setPuntosNegativos(generateRandom(Integer.class));
		ldto.setCarrera(generateRandom(String.class));
		
		
		monitorLogicService.updateMonitor(ldto);
		
		
		MonitorDTO resp=monitorPersistence.getMonitor(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getActivo(), resp.getActivo());	
		Assert.assertEquals(ldto.getUsuario(), resp.getUsuario());	
		Assert.assertEquals(ldto.getPuntosNegativos(), resp.getPuntosNegativos());	
		Assert.assertEquals(ldto.getCarrera(), resp.getCarrera());	
	}
	
	@Test
	public void getMonitorPaginationTest(){
		
		MonitorPageDTO dto1=monitorLogicService.getMonitors(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		MonitorPageDTO dto2=monitorLogicService.getMonitors(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(MonitorDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(MonitorDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(MonitorDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(MonitorDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        MonitorPageDTO dto3=monitorLogicService.getMonitors(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(MonitorDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(MonitorDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}