/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.Matisse.resultado.persistence;

import co.edu.uniandes.csw.Matisse.API.ServiciosAPI;
import co.edu.uniandes.csw.Matisse.pregunta.logic.dto.PreguntaDTO;
import co.edu.uniandes.csw.Matisse.resultado.logic.dto.ResultadoDTO;
import co.edu.uniandes.csw.Matisse.resultado.logic.dto.ResultadoPageDTO;
import co.edu.uniandes.csw.Matisse.resultado.persistence.api.IResultadoPersistence;
import co.edu.uniandes.csw.Matisse.resultado.persistence.converter.ResultadoConverter;
import co.edu.uniandes.csw.Matisse.resultado.persistence.entity.ResultadoEntity;
import static co.edu.uniandes.csw.Matisse.util._TestUtil.*;
import java.util.*;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;
import org.codehaus.jettison.json.JSONObject;
import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(Arquillian.class)
public class ResultadoPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ResultadoPersistence.class.getPackage())
				.addPackage(ResultadoEntity.class.getPackage())
				.addPackage(IResultadoPersistence.class.getPackage())
                .addPackage(ResultadoDTO.class.getPackage())
                .addPackage(ResultadoConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IResultadoPersistence resultadoPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from ResultadoEntity").executeUpdate();
	}

	private List<ResultadoEntity> data=new ArrayList<ResultadoEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ResultadoEntity entity=new ResultadoEntity();
			entity.setName(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createResultadoTest(){
		ResultadoDTO dto=new ResultadoDTO();
		dto.setName(generateRandom(String.class));
		
		ResultadoDTO result=resultadoPersistence.createResultado(dto);
		
		Assert.assertNotNull(result);
		
		ResultadoEntity entity=em.find(ResultadoEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
	}
	
	@Test
	public void getResultadosTest(){
		List<ResultadoDTO> list=resultadoPersistence.getResultados();
		Assert.assertEquals(list.size(), data.size());
        for(ResultadoDTO dto:list){
        	boolean found=false;
            for(ResultadoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getResultadoTest(){
		ResultadoEntity entity=data.get(0);
		ResultadoDTO dto=resultadoPersistence.getResultado(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
        
	}
	
	@Test
	public void deleteResultadoTest(){
		ResultadoEntity entity=data.get(0);
		resultadoPersistence.deleteResultado(entity.getId());
        ResultadoEntity deleted=em.find(ResultadoEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateResultadoTest(){
		ResultadoEntity entity=data.get(0);
		
		ResultadoDTO dto=new ResultadoDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		
		
		resultadoPersistence.updateResultado(dto);
		
		
		ResultadoEntity resp=em.find(ResultadoEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
	}
        
        @Test
        public void obtenerPregunaDe4API(){
            ServiciosAPI lm = ServiciosAPI.getInstance();
            JSONObject array = lm.getQuestionsProperties(3);
            Assert.assertNotNull(array);
        }
        
        
        @Test
        public void obtenerRespuestas(){
            ServiciosAPI lm = ServiciosAPI.getInstance();
            Assert.assertNotNull(lm.exportResponses());
        }
        
        
        @Test
        public void obtenerGrupos(){
            ServiciosAPI lm = ServiciosAPI.getInstance();
            Assert.assertNotNull(lm.listGroups(ResultadoPersistence.ID_SURVEY));
        }
        
        @Test
        public void obtenerPreguntasGrupo(){
            ServiciosAPI lm = ServiciosAPI.getInstance();
            Assert.assertNotNull(lm.listQuestions(ResultadoPersistence.ID_SURVEY, 6));
        }
        
        @Test
        public void obtenerPreguntaDe5(){
            PreguntaDTO preg = resultadoPersistence.respuestaA(11);
            Assert.assertNotNull(preg);
        }
	
        @Test
        public void obtenerPreguntaDe4(){
            PreguntaDTO preg = resultadoPersistence.respuestaA(1);
            Assert.assertNotNull(preg);
        }
        
        @Test
        public void obtenerListaPreguntas(){
            List<PreguntaDTO> pregus = resultadoPersistence.listarPreguntas();
            Assert.assertNotNull(pregus);
        }
        
	@Test
	public void getResultadoPaginationTest(){
		//Page 1
		ResultadoPageDTO dto1=resultadoPersistence.getResultados(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        ResultadoPageDTO dto2=resultadoPersistence.getResultados(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(ResultadoDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(ResultadoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ResultadoDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ResultadoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}