/* ========================================================================
 * Copyright 2014 Matisse
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Matisse
  
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
  
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
  
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 * ========================================================================
  
  
 Source generated by CrudMaker version 1.0.0.201411201032*/
package co.edu.uniandes.csw.Matisse.resultado.master.persistence;

import co.edu.uniandes.csw.Matisse.entradas.logic.dto.EntradasDTO;
import co.edu.uniandes.csw.Matisse.resultado.master.persistence.entity.ResultadoentradasEntity;
import co.edu.uniandes.csw.Matisse.entradas.persistence.converter.EntradasConverter;
import co.edu.uniandes.csw.Matisse.resultado.logic.dto.ResultadoDTO;
import co.edu.uniandes.csw.Matisse.resultado.master.logic.dto.ResultadoMasterDTO;
import co.edu.uniandes.csw.Matisse.resultado.master.persistence.api._IResultadoMasterPersistence;
import co.edu.uniandes.csw.Matisse.resultado.persistence.api.IResultadoPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _ResultadoMasterPersistence implements _IResultadoMasterPersistence {

    @PersistenceContext(unitName = "CupiTallerPU")

    protected EntityManager entityManager;

    @Inject
    protected IResultadoPersistence resultadoPersistence;

    public ResultadoMasterDTO getResultado(Long resultadoId) {
        ResultadoMasterDTO resultadoMasterDTO = new ResultadoMasterDTO();
        ResultadoDTO resultado = resultadoPersistence.getResultado(resultadoId);
        resultadoMasterDTO.setResultadoEntity(resultado);
        resultadoMasterDTO.setListentradas(getResultadoentradasEntityList(resultadoId));
        return resultadoMasterDTO;
    }

    public ResultadoentradasEntity createResultadoentradasEntity(ResultadoentradasEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteResultadoentradasEntity(Long resultadoId, Long entradasId) {
        Query q = entityManager.createNamedQuery("ResultadoentradasEntity.deleteResultadoentradasEntity");
        q.setParameter("resultadoId", resultadoId);
        q.setParameter("entradasId", entradasId);
        q.executeUpdate();
    }

    public List<EntradasDTO> getResultadoentradasEntityList(Long resultadoId) {
        ArrayList<EntradasDTO> resp = new ArrayList<EntradasDTO>();
        Query q = entityManager.createNamedQuery("ResultadoentradasEntity.getByMasterId");
        q.setParameter("resultadoId", resultadoId);
        List<ResultadoentradasEntity> qResult = q.getResultList();
        for (ResultadoentradasEntity entity : qResult) {
            if (entity.getEntradasIdEntity() == null) {
                entityManager.refresh(entity);
            }
            resp.add(EntradasConverter.entity2PersistenceDTO(entity.getEntradasIdEntity()));
        }
        return resp;
    }

}
