/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.Matisse.resultado.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.Matisse.resultado.logic.dto.ResultadoPageDTO;
import co.edu.uniandes.csw.Matisse.resultado.logic.dto.ResultadoDTO;
import co.edu.uniandes.csw.Matisse.resultado.logic.api.IResultadoLogicService;
import co.edu.uniandes.csw.Matisse.resultado.persistence.ResultadoPersistence;
import co.edu.uniandes.csw.Matisse.resultado.persistence.api.IResultadoPersistence;
import co.edu.uniandes.csw.Matisse.resultado.persistence.entity.ResultadoEntity;
import co.edu.uniandes.csw.Matisse.resultado.persistence.converter.ResultadoConverter;
import static co.edu.uniandes.csw.Matisse.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ResultadoLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ResultadoLogicService.class.getPackage())
				.addPackage(IResultadoLogicService.class.getPackage())
				.addPackage(ResultadoPersistence.class.getPackage())
				.addPackage(ResultadoEntity.class.getPackage())
				.addPackage(IResultadoPersistence.class.getPackage())
                .addPackage(ResultadoDTO.class.getPackage())
                .addPackage(ResultadoConverter.class.getPackage())
                .addPackage(ResultadoEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IResultadoLogicService resultadoLogicService;
	
	@Inject
	private IResultadoPersistence resultadoPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<ResultadoDTO> dtos=resultadoPersistence.getResultados();
		for(ResultadoDTO dto:dtos){
			resultadoPersistence.deleteResultado(dto.getId());
		}
	}

	private List<ResultadoDTO> data=new ArrayList<ResultadoDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ResultadoDTO pdto=new ResultadoDTO();
			pdto.setName(generateRandom(String.class));
			pdto=resultadoPersistence.createResultado(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createResultadoTest(){
		ResultadoDTO ldto=new ResultadoDTO();
		ldto.setName(generateRandom(String.class));
		
		
		ResultadoDTO result=resultadoLogicService.createResultado(ldto);
		
		Assert.assertNotNull(result);
		
		ResultadoDTO pdto=resultadoPersistence.getResultado(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
	}
	
	@Test
	public void getResultadosTest(){
		List<ResultadoDTO> list=resultadoLogicService.getResultados();
		Assert.assertEquals(list.size(), data.size());
        for(ResultadoDTO ldto:list){
        	boolean found=false;
            for(ResultadoDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getResultadoTest(){
		ResultadoDTO pdto=data.get(0);
		ResultadoDTO ldto=resultadoLogicService.getResultado(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
        
	}
	
	@Test
	public void deleteResultadoTest(){
		ResultadoDTO pdto=data.get(0);
		resultadoLogicService.deleteResultado(pdto.getId());
        ResultadoDTO deleted=resultadoPersistence.getResultado(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateResultadoTest(){
		ResultadoDTO pdto=data.get(0);
		
		ResultadoDTO ldto=new ResultadoDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		
		
		resultadoLogicService.updateResultado(ldto);
		
		
		ResultadoDTO resp=resultadoPersistence.getResultado(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
	}
	
	@Test
	public void getResultadoPaginationTest(){
		
		ResultadoPageDTO dto1=resultadoLogicService.getResultados(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		ResultadoPageDTO dto2=resultadoLogicService.getResultados(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(ResultadoDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(ResultadoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ResultadoDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ResultadoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        ResultadoPageDTO dto3=resultadoLogicService.getResultados(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(ResultadoDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(ResultadoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}