/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201408112050*/

package co.edu.uniandes.csw.Matisse.encuesta.master.logic.ejb;

import co.edu.uniandes.csw.Matisse.pregunta.logic.dto.PreguntaDTO;
import co.edu.uniandes.csw.Matisse.pregunta.persistence.api.IPreguntaPersistence;
import co.edu.uniandes.csw.Matisse.encuesta.logic.dto.EncuestaDTO;
import co.edu.uniandes.csw.Matisse.encuesta.master.logic.api._IEncuestaMasterLogicService;
import co.edu.uniandes.csw.Matisse.encuesta.master.logic.dto.EncuestaMasterDTO;
import co.edu.uniandes.csw.Matisse.encuesta.master.persistence.api.IEncuestaMasterPersistence;
import co.edu.uniandes.csw.Matisse.encuesta.master.persistence.entity.EncuestapreguntasEntity;
import co.edu.uniandes.csw.Matisse.encuesta.persistence.api.IEncuestaPersistence;
import javax.inject.Inject;

public abstract class _EncuestaMasterLogicService implements _IEncuestaMasterLogicService {

    @Inject
    protected IEncuestaPersistence encuestaPersistance;
    @Inject
    protected IEncuestaMasterPersistence encuestaMasterPersistance;
    @Inject
    protected IPreguntaPersistence preguntaPersistance;

    public EncuestaMasterDTO createMasterEncuesta(EncuestaMasterDTO encuesta) {
        EncuestaDTO persistedEncuestaDTO = encuestaPersistance.createEncuesta(encuesta.getEncuestaEntity());
        if (encuesta.getCreatepreguntas() != null) {
            for (PreguntaDTO preguntaDTO : encuesta.getCreatepreguntas()) {
                PreguntaDTO createdPreguntaDTO = preguntaPersistance.createPregunta(preguntaDTO);
                EncuestapreguntasEntity encuestaPreguntaEntity = new EncuestapreguntasEntity(persistedEncuestaDTO.getId(), createdPreguntaDTO.getId());
                encuestaMasterPersistance.createEncuestapreguntasEntity(encuestaPreguntaEntity);
            }
        }
        // update pregunta
        if (encuesta.getUpdatepreguntas() != null) {
            for (PreguntaDTO preguntaDTO : encuesta.getUpdatepreguntas()) {
                preguntaPersistance.updatePregunta(preguntaDTO);
                EncuestapreguntasEntity encuestaPreguntaEntity = new EncuestapreguntasEntity(persistedEncuestaDTO.getId(), preguntaDTO.getId());
                encuestaMasterPersistance.createEncuestapreguntasEntity(encuestaPreguntaEntity);
            }
        }
        return encuesta;
    }

    public EncuestaMasterDTO getMasterEncuesta(Long id) {
        return encuestaMasterPersistance.getEncuesta(id);
    }

    public void deleteMasterEncuesta(Long id) {
        encuestaPersistance.deleteEncuesta(id);
    }

    public void updateMasterEncuesta(EncuestaMasterDTO encuesta) {
        encuestaPersistance.updateEncuesta(encuesta.getEncuestaEntity());

        //---- FOR RELATIONSHIP
        // persist new pregunta
        if (encuesta.getCreatepreguntas() != null) {
            for (PreguntaDTO preguntaDTO : encuesta.getCreatepreguntas()) {
                PreguntaDTO createdPreguntaDTO = preguntaPersistance.createPregunta(preguntaDTO);
                EncuestapreguntasEntity encuestaPreguntaEntity = new EncuestapreguntasEntity(encuesta.getEncuestaEntity().getId(), createdPreguntaDTO.getId());
                encuestaMasterPersistance.createEncuestapreguntasEntity(encuestaPreguntaEntity);
            }
        }
        // update pregunta
        if (encuesta.getUpdatepreguntas() != null) {
            for (PreguntaDTO preguntaDTO : encuesta.getUpdatepreguntas()) {
                preguntaPersistance.updatePregunta(preguntaDTO);
            }
        }
        // delete pregunta
        if (encuesta.getDeletepreguntas() != null) {
            for (PreguntaDTO preguntaDTO : encuesta.getDeletepreguntas()) {
                encuestaMasterPersistance.deleteEncuestapreguntasEntity(encuesta.getEncuestaEntity().getId(), preguntaDTO.getId());
                preguntaPersistance.deletePregunta(preguntaDTO.getId());
            }
        }
    }
}
