/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.Matisse.resultado.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.Matisse.resultado.logic.dto.ResultadoDTO;
import co.edu.uniandes.csw.Matisse.resultado.logic.api.IResultadoLogicService;
import co.edu.uniandes.csw.Matisse.resultado.master.logic.api._IResultadoMasterLogicService;
import co.edu.uniandes.csw.Matisse.resultado.master.logic.dto.ResultadoMasterDTO;
import co.edu.uniandes.csw.Matisse.entradas.logic.api.IEntradasLogicService;
import co.edu.uniandes.csw.Matisse.entradas.logic.dto.EntradasDTO;
import javax.inject.Inject;


public abstract class _ResultadoMasterMockLogicService implements _IResultadoMasterLogicService {

    protected static ArrayList<ResultadoMasterDTO> resultadoMasterDtosList = new ArrayList<ResultadoMasterDTO>() ;
    @Inject
    protected IEntradasLogicService entradasPersistance;
    @Inject
    protected IResultadoLogicService resultadoPersistance;

    public ResultadoMasterDTO createMasterResultado(ResultadoMasterDTO resultado) {

        resultadoPersistance.createResultado(resultado.getResultadoEntity());
        for (EntradasDTO dto : resultado.getCreateentradas()) {
            entradasPersistance.createEntradas(dto);
        }
        resultadoMasterDtosList.add(resultado);
        return resultado;
    }

    public ResultadoMasterDTO getMasterResultado(Long id) {
        for (ResultadoMasterDTO resultadoMasterDTO : resultadoMasterDtosList) {
            if (resultadoMasterDTO.getResultadoEntity().getId() == id) {
                return resultadoMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterResultado(Long id) {
        for (ResultadoMasterDTO resultadoMasterDTO : resultadoMasterDtosList) {
            if (resultadoMasterDTO.getResultadoEntity().getId() == id) {

                for (EntradasDTO dto : resultadoMasterDTO.getCreateentradas()) {
                    entradasPersistance.deleteEntradas(dto.getId());
                }
                resultadoPersistance.deleteResultado(resultadoMasterDTO.getId());
                resultadoMasterDtosList.remove(resultadoMasterDTO);
            }
        }

    }

    public void updateMasterResultado(ResultadoMasterDTO resultado) {

        // update Entradas
        if (resultado.getUpdateentradas() != null) {
            for (EntradasDTO dto : resultado.getUpdateentradas()) {
                entradasPersistance.updateEntradas(dto);
            }
        }
        // persist new Entradas
        if (resultado.getCreateentradas() != null) {
            for (EntradasDTO dto : resultado.getCreateentradas()) {
                EntradasDTO persistedEntradasDTO = entradasPersistance.createEntradas(dto);
                dto = persistedEntradasDTO;
            }
        }
        // delete Entradas
        if (resultado.getDeleteentradas() != null) {
            for (EntradasDTO dto : resultado.getDeleteentradas()) {

                entradasPersistance.deleteEntradas(dto.getId());
            }
        }
    }
}