/* ========================================================================
   * Copyright 2014 Matisse
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 Matisse
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201408112050*/

package co.edu.uniandes.csw.Matisse.encuesta.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.Matisse.encuesta.logic.dto.EncuestaDTO;
import co.edu.uniandes.csw.Matisse.encuesta.logic.api.IEncuestaLogicService;
import co.edu.uniandes.csw.Matisse.encuesta.master.logic.api._IEncuestaMasterLogicService;
import co.edu.uniandes.csw.Matisse.encuesta.master.logic.dto.EncuestaMasterDTO;
import co.edu.uniandes.csw.Matisse.pregunta.logic.api.IPreguntaLogicService;
import co.edu.uniandes.csw.Matisse.pregunta.logic.dto.PreguntaDTO;
import javax.inject.Inject;


public abstract class _EncuestaMasterMockLogicService implements _IEncuestaMasterLogicService {

    protected static ArrayList<EncuestaMasterDTO> encuestaMasterDtosList = new ArrayList<EncuestaMasterDTO>() ;
    @Inject
    protected IPreguntaLogicService preguntaPersistance;
    @Inject
    protected IEncuestaLogicService encuestaPersistance;

    public EncuestaMasterDTO createMasterEncuesta(EncuestaMasterDTO encuesta) {

        encuestaPersistance.createEncuesta(encuesta.getEncuestaEntity());
        for (PreguntaDTO dto : encuesta.getCreatepreguntas()) {
            preguntaPersistance.createPregunta(dto);
        }
        encuestaMasterDtosList.add(encuesta);
        return encuesta;
    }

    public EncuestaMasterDTO getMasterEncuesta(Long id) {
        for (EncuestaMasterDTO encuestaMasterDTO : encuestaMasterDtosList) {
            if (encuestaMasterDTO.getEncuestaEntity().getId() == id) {
                return encuestaMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterEncuesta(Long id) {
        for (EncuestaMasterDTO encuestaMasterDTO : encuestaMasterDtosList) {
            if (encuestaMasterDTO.getEncuestaEntity().getId() == id) {

                for (PreguntaDTO dto : encuestaMasterDTO.getCreatepreguntas()) {
                    preguntaPersistance.deletePregunta(dto.getId());
                }
                encuestaPersistance.deleteEncuesta(encuestaMasterDTO.getId());
                encuestaMasterDtosList.remove(encuestaMasterDTO);
            }
        }

    }

    public void updateMasterEncuesta(EncuestaMasterDTO encuesta) {

        // update Pregunta
        if (encuesta.getUpdatepreguntas() != null) {
            for (PreguntaDTO dto : encuesta.getUpdatepreguntas()) {
                preguntaPersistance.updatePregunta(dto);
            }
        }
        // persist new Pregunta
        if (encuesta.getCreatepreguntas() != null) {
            for (PreguntaDTO dto : encuesta.getCreatepreguntas()) {
                PreguntaDTO persistedPreguntaDTO = preguntaPersistance.createPregunta(dto);
                dto = persistedPreguntaDTO;
            }
        }
        // delete Pregunta
        if (encuesta.getDeletepreguntas() != null) {
            for (PreguntaDTO dto : encuesta.getDeletepreguntas()) {

                preguntaPersistance.deletePregunta(dto.getId());
            }
        }
    }
}